"""add connection type to action and serial to user device

Revision ID: b52c4ba70e00
Revises: 1401f0319229
Create Date: 2024-05-11 18:47:51.107892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52c4ba70e00'
down_revision = '1401f0319229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', name='requestmethod'), nullable=True))
        batch_op.add_column(sa.Column('connection_protocol', sa.Enum('HTTP', 'HTTPS', 'MQTT', name='connectionprotocol'), nullable=True))

    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_column('serial')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('connection_protocol')
        batch_op.drop_column('request_method')

    # ### end Alembic commands ###
