"""add_contribution_id_and_author_id

Revision ID: d778846ae61e
Revises: b52c4ba70e00
Create Date: 2024-05-20 20:49:41.309005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd778846ae61e'
down_revision = 'b52c4ba70e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrituion_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key("authors_id_id", 'authors', ['author_id'], ['id'])

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contribution_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key("authors_id_id", 'authors', ['author_id'], ['id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('contribution_id', sa.UUID(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key("authors_id_id", 'authors', ['author_id'], ['id'])

    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.NUMERIC(), nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('contribution_id')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('contribution_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('contrituion_id')

    # ### end Alembic commands ###
